name: "CI"
on:
  push:

jobs:
  test-events:
    runs-on: [ubuntu-latest]
    steps:
      - name: Summary
        run: |
          echo "### Summary of things! :rocket:" >> $GITHUB_STEP_SUMMARY
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Build
        run: npm run build
      - name: Deploy staging
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          npx surge --project ./build --domain six-lunch.surge.sh

